### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/serenata-toolbox#136]
Hi as many know, it can be scary to give your first contribution to open source. And sometimes you may need help to start contributing to a new project.

Thinking of that and reading [First Timers Only website for hints](http://www.firsttimersonly.com) we thought would be nice to do two things:

1. Create the `first-timers-only` label: Done
1. Create a template to help people opening up a new issue.

So [here is the first draft of a `issue_template`](https://gist.github.com/jtemporal/5c5de029b6e05854f4a2d09cfe9220bf) to be added to this and all of the other Serenata's repositories.

This issue will be open to collect ideas on how to make this template as friendly as possible but also generic so everyone can feel comfortable using it. Any feedback is much appreciated 😉

Special thanks to @lipemorais who helped in coming up with this ❤️

**Comment by anaschwendler** [comment]
@jtemporal 
Maybe in the first line you can use:

Issue Template -> Here add the name of the Issue/ Pull Request

"This template is here to help you to write your issue ;)" -> introduce here the problem

And it is OK to me ;)

**Comment by rodolfo-viana** [comment]
As a newbie, I just want to say it warms my heart to see this going on.

**Comment by renatooliveira** [comment]
Here at @labcodes we use checklists for everything. We don't have an issue template but here is our pull request template

https://gist.github.com/renatooliveira/09418592b8891f663f3060f2f61e891f

**Comment by cuducos** [comment]
At first I must say the _only_ in _first timers only_ bugged me — specially in these two hypothetical scenarios:

* We find out about a simple bug, open an issue and label it _first timers only_. Later on we find out that big is blocking something else and should de fixed ASAP. So this creates an urgency that doesn't have a fit with waiting for a first timer contributor to pop in. We'll have to fix a _first timers only_ issue.
* If is there an issue labeled with _first timers only_  but a contributor that is not a first timer open a PR fixing it — should we accept the PR or decline it saying _Closed because you're not a first timer_.

Both situations might be harmful for the project: the first one delays progress, the second one might discourage someone that has dedicated time to the project.

**However** when I shared this thoughts with @jtemporal she responded with:

>It's a worldwide standard, I like it it is an worldwide standard — and `Special cases aren't special enough to break the rules`.

And I followed:

> And `practicality beats purity`.

And that is the story when I got convinced this is in fact a really good idea.

**Comment by Lrodlima** [comment]
I just loved !

**Comment by cuducos** [comment]
Closed by #137

**Comment by gr2m** [comment]
Hey I just found out about this by chance :) I think you’d enjoy https://github.com/apps/first-timers let me know if you have any questions
