### ISSUE TITLE
What should our tests do?

### ISSUE THREAD

**Issue by lipemorais** [datasciencebr/serenata-toolbox#146]
**What is the problem?**
I can see through some PR's decisions that the definitions of tests are differents. Specially about what should journey tests cover and do.

**How can this be addressed?**
I believe that after a discussion a simple Markdown file inside the project could keep this definition inside the project.

**Who could help with this issue?**
I think that @Irio @jtemporal @cuducos @anaschwendler could contribute to this discussion.

**What I want from you?**
Share with us here answers for 3 questions:
- What should tests do and covers in general?
- What should `unit-tests` do and cover?
- What should `journey-tests` do and cover?

All of it focused on Serenata Toolbox context.

**Labels**
[question]

**Comment by cuducos** [comment]
Taking my first guesses:

> What should tests do and covers in general?

The toolbox tests should assert that given an expected input (e.g. a fixture simulating the structure of a real world a dataset) the output is what we wanted.

> What should `unit-tests` do and cover?

Unit tests should test each function/method, isolating it from any environment or side-effect (use and abuse of mocks, for example).

> What should `journey-tests` do and cover?

They should depart for a controlled input (fixtures) to test the integration os all the pieces: given the input it should really create the output file, for example — without depending on any external eventuality (mock the input if it comes from a remote server, for example).

**Comment by lipemorais** [comment]
> What should tests do and covers in general?

The Serenata Toolbox tests should protect us from our on mistakes providing safety to move on and help us keep everything working while we keep improving our project.

> What should unit-tests do and cover?

The unit-tests should cover the smallest unit of code. Unless it covers a piece of code that don't have coverage. What happens on project that do not have 100% of code coverage and is usual.

> What should journey-tests do and cover?

In my vision it has two principal values:
- Test real journey based on real value **but mocked**
- Test real journey based on **real integration** before we deploy to assure that everything is ok with our integration.

**Comment by cuducos** [comment]
> Test real journey based on **real integration** before we deploy to assure that everything is ok with our integrations.

Experience has shown us that relying on external services (specially on government one I might add) is problematic: they are unstable, they change format/encoding without warning, etc.

This argument actually  goes both ways: on the one hand we must get used to see our CI red not because we messes up, but because these external servers did it. On the other hand we must be sure the toolbox works with them before releasing a new version.

What really bugs me is that the instability is way more common than unwanted changes in their side… so we'll be blocked most of the times just because of low availability of third-parties.

**Comment by lipemorais** [comment]
> Experience has shown us that relying on external services (specially on government one I might add) is problematic: they are unstable, they change format/encoding without warning, etc.

There is a advantage of `monitor` the external service that is know as soon as possible the changes on their side.

> On the other hand we must be sure the toolbox works with them before releasing a new version.

I believe that will depends on the kind of break. 
- If it's for instability of external service. We should move on.
- If it's for format changing or encoding. We should **not** move on.

> so we'll be blocked most of the times just because of low availability of third-parties.

We should not be stopped by instability just for really breaking changes from the external services.

**Comment by cuducos** [comment]
> There is a advantage of `monitor` the external service that is know as soon as possible the changes on their side.

This in in fact important… however IMHO it's not the role expected from the test suite.

**Comment by lipemorais** [comment]
> This in in fact important… however IMHO it's not the role expected from the test suite.

Which alternative do we have to keep this important point and a suite that do not have external dependencies?

I can think a pipeline like:

`unit-test` => `mocked-integration-tests` => `deploy` => `integration-tests-with-**real-external-service**`

Or  have  just:

`unit-test` => `mocked-integration-tests` => `deploy`

and a second stuff like [status.io](https://status.github.com/messages) specific for what we have as external dependency.

**Comment by jtemporal** [comment]
The toolbox today depends on third parties to work right, or at least every time that we open up a new PR we are open to a red CI because of third parties like @cuducos said:
>on the one hand we must get used to see our CI red not because we messed up, but because these external servers did it.

I think the ideal question is: How to test everything without going crazy on testing?

> What should tests do and covers in general?

given an input the output is what is expected

>What should unit-tests do and cover?

the minimum amount of code, e.g.: a function that translates should receive a dataset in pt-br and return a dataset in en, so the test is "given the dataset `a` in pt-br the output of the translate function was the dataset `a` in en? if so then the test pass otherwise it shouldn't

> What should journey-tests do and cover?
If the whole process is working. The toolbox is a pipeline it has a beginning and a path to be followed  until the end, do all of those steps being done? and working as they should?

On the matter of integration tests: Toolbox is the point that encounters "the outside world" on the project" especially considering Rosie. We definitely need some integration tests. But the integration should more raise an alert out than block us from improving our toolbox.

**Comment by anaschwendler** [comment]
> What should tests do and covers in general?
The tests must cover all the inputs generating expected outputs, but not only that, I think that we need to think about the behavior and use the tests to try easier ways to perform the system as it is.

> What should unit-tests do and cover?
Little slices of code, as @jtemporal said.

> What should journey-tests do and cover?
The behavior that toolbox should perform to other repos. But at this point I don't know if we should work for a repo that make everything works, or we still work on separate repos.

The big refactor is to fix things and make them easier, so I can't think only about toolbox when I ask myself those questions

**Comment by Irio** [comment]
@cuducos' comment summarizes well my view on the topic.

When removing "real integration" tests, we lose the ability to know when the Congress changes its file formats or becomes offline (which happened often in the past months, affecting our project in multiple instances). They could be replaced by a simple status page, as mentioned before, with online status (on/off) and some sanity checks on the data (e.g. is a zip file? contains a csv? has a given list of columns? has more rows than the last update?).

**Comment by lipemorais** [comment]
My conclusion with this is that even that when we have an instability from externals we should move on without this checks. Like a `nice to have` but not a `must have`.

**Comment by cuducos** [comment]
Yes… as far as I got these checks are not part of automated tests. They're something else ; )

**Comment by cuducos** [comment]
Archived by inactivity — anyone is free to re-open when needed ; )
