### ISSUE TITLE
[Question] New contributors

### ISSUE THREAD

**Issue by allan-silva** [datasciencebr/serenata-toolbox#168]
Hey, that is a cool project!
There are, for new contributors, specific issues? Or , there is another place where issues available for community are listed?

**Comment by cuducos** [comment]
Hi @allan-silva,

Usually we have the [first-timers only](https://github.com/datasciencebr/serenata-toolbox/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only) labels on our repo, but right now there's no issue in the toolbox itself. Maybe you can look the ones on the other repos:

* [Serenta de Amor](https://github.com/datasciencebr/serenata-de-amor/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only)
* [Rosie](https://github.com/datasciencebr/rosie/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only)
* [Josie](https://github.com/datasciencebr/jarbas/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only)
* [Whistleblower](https://github.com/datasciencebr/whistleblower/issues?q=is%3Aopen+is%3Aissue+label%3Afirst-timers-only)

Actually only the main repo (Serenata de Amor) has issues labeled for newcomers at the moment, but I leave you with the links because that might change over time ; )

**Comment by cuducos** [comment]
Also, if you're a beginner, you might want to take a look in our [main repo contributing guide](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md
) and in [this post with a bit of our architecture](https://datasciencebr.com/how-does-one-contribute-to-serenata-de-amor-operation-36e3e7b38207 
) 🎉

**Comment by allan-silva** [comment]
Thanks @cuducos, I'll take a look! Currently I contribute with other open source projects, but serenata de amor seems a very interesting brazilian project.

**Comment by cuducos** [comment]
We're glad to have you around here ; ) Make yourself at home.
